MvcStok/Controllers/MüşteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class MüşteriController : Controller
    {

        MvcDbStokEntities db = new MvcDbStokEntities();

        //burda bir parametre aracılığıyla değerleri gönderip kontrol edeceğiz.
        public ActionResult MüşteriListesi(string p)
        {
            // d yi müsteri tablosundan çek ve d ye ata select d d ye ata demek
            var degerler = from d in db.TBL_MUSTERİ select d;

            //string olan p boş veya null değilse bunu yap
            if (!string.IsNullOrEmpty(p))
            {
                //değerlere müşteri adında p geçenleri ekle
                degerler = degerler.Where(m => m.müsteriad.Contains(p));
            }

            return View(degerler.ToList());

            //var values = db.TBL_MUSTERİ.ToList(); 
            //return View(values);
        }


        [HttpGet]
        public ActionResult YeniMüşteri() 
        {
            return View();
        
        }

        [HttpPost]
        public ActionResult YeniMüşteri(TBL_MUSTERİ musteri)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniMüşteri");
            }
            db.TBL_MUSTERİ.Add(musteri);
            db.SaveChanges();
            return RedirectToAction("MüşteriListesi");

        }

        public ActionResult Sil(int id)
        {
            var silinecekdeğer = db.TBL_MUSTERİ.Find(id);
            db.TBL_MUSTERİ.Remove(silinecekdeğer);
            db.SaveChanges();
            return RedirectToAction("MüşteriListesi");
        }

        public ActionResult MüşteriGetir(int id)
        {
            var value = db.TBL_MUSTERİ.Find(id);
            return View("MüşteriGetir",value);
        }

        public ActionResult Güncelle(TBL_MUSTERİ p1) 
        {
            var value = db.TBL_MUSTERİ.Find(p1.müsteriıd);
            value.müsteriad = p1.müsteriad;
            value.müsterisoyad = p1.müsterisoyad;
            db.SaveChanges();
            return RedirectToAction("MüşteriListesi");
        }
    }
}

MvcStok/Views/Müşteri/MüşteriGetir.cshtml
@model MvcStok.Models.Entity.TBL_MUSTERİ
@{
    ViewBag.Title = "MüşteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Müşteri Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("Güncelle","Müşteri",FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(m => m.müsteriıd, "MÜŞTERİ ID")
    @Html.TextBoxFor(m => m.müsteriıd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.müsteriad, "MÜŞTERİ AD")
    @Html.TextBoxFor(m => m.müsteriad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.müsterisoyad, "MÜŞTERİ SOYAD")
    @Html.TextBoxFor(m => m.müsterisoyad, new { @class = "form-control" })
    <br />

</div>
<div><button class="btn btn-warning">MÜŞTERİ GÜNCELLE</button></div>
}

MvcStok/Views/Müşteri/MüşteriListesi.cshtml
@using MvcStok.Models.Entity
@model List<TBL_MUSTERİ>

@{
    ViewBag.Title = "MüşteriListesi";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<br />

@using (Html.BeginForm("MüşteriListesi", "Müşteri", FormMethod.Get))
{
    <p>
        <b> Aranacak Müşteri Adı:</b> @Html.TextBox("p")
        <input type="submit" value="Ara" class="btn btn-info"/>
    </p>
}
<br />
<table class="table table-bordered">
    <tr>
        <th>Müşteri ID</th>
        <th>Müşteri ADI</th>
        <th>Müşteri Soyadı</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>ALERT</th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.müsteriıd</td>
            <td>@item.müsteriad</td>
            <td>@item.müsterisoyad</td>
            <td><a href="/Müşteri/Sil/@item.müsteriıd" class="btn btn-danger">SİL</a></td>
            <td><a href="/Müşteri/MüşteriGetir/@item.müsteriıd" class="btn btn-success">GÜNCELLE</a></td>

            <td>@Html.ActionLink("SİL BUTONU", "Sil", new { id = item.müsteriıd }, new { @class = "btn btn-warning", onclick = "return confirm('Gerçekten Silmek İstiyor Musunuz?')" })  </td>


        </tr>
    }



</table>
<a href="/Müşteri/YeniMüşteri/" class="btn btn-info">YENİ MÜŞTERİ EKLE</a>

MvcStok/Views/Müşteri/YeniMüşteri.cshtml
@model MvcStok.Models.Entity.TBL_MUSTERİ
@{
    ViewBag.Title = "YeniMüşteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h3>Yeni Müşteri Ekleme Sayfası</h3>
<br /><br />

<form class="form-group" method="post">
    <div>
        <label>Müşteri Adı</label>
        @*<input type="text" class="form-control" name="müsteriad"/>
        <br /><br />*@

        @Html.TextBoxFor(m => m.müsteriad, new { @class = "form-control" })
        <br />

        @Html.ValidationMessageFor(m => m.müsteriad, "", new { @style = "color:green" })
        <br /><br />
        <label>Müşteri Soyadı</label>
        <input type="text" class="form-control" name="müsterisoyad" />
        <br /><br />
        <button class="btn btn-info" id="btn1">MÜŞTERİ EKLE</button>
    </div>
    <script>
        $('#btn1').click(function () {

            alert('Müşteri Ekleme İşlemi Yapıldı...');

        });


    </script>


</form>