MvcStok/Controllers/UrunlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class UrunlerController : Controller
    {
        MvcDbStokEntities db = new MvcDbStokEntities();

        public ActionResult ÜrünListesi(string a)
        {
            //var values = from c in db.TBL_URUNLER select c;

            //if (!string.IsNullOrEmpty(a))
            //{
            //    values = values.Where(m=>m.ürünadı.Contains(a));
            //}

            //return View(values.ToList());


            var value = db.TBL_URUNLER.ToList();
            return View(value);
        }

        [HttpGet]
        public ActionResult YeniÜrün()
        {
            //listeden öğe seç anlamına gelen yapı= kategori tablosunun listesini çek ve i ye ata 
            //bu listeyi seç (selectlistitem)
            //seçilen listenin text değeri i den gelen ad
            //value =i nin kategori id si
            // i de tbl kategoriden gelen değerleri ad ve id ye eşitlememizi sağlıyor
            List<SelectListItem> degerler = (from i in db.TBL_KATEGORİLER.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.kategoriad,
                                                 Value = i.kategoriıd.ToString(),

                                             }).ToList();
            ViewBag.deger = degerler;                                           
            return View();

        }

        [HttpPost]
        public ActionResult YeniÜrün(TBL_URUNLER urun)
        {

            //kategoriyi dropdowndan seçip ekliycez.
            var kategori = db.TBL_KATEGORİLER.Where(m=>m.kategoriıd == urun.TBL_KATEGORİLER.kategoriıd).FirstOrDefault();
            urun.TBL_KATEGORİLER = kategori;
            db.TBL_URUNLER.Add(urun);
            db.SaveChanges();
            return RedirectToAction("ÜrünListesi");

        }

        public ActionResult Sil(int id)
        {
            var value = db.TBL_URUNLER.Find(id);
            db.TBL_URUNLER.Remove(value);
            db.SaveChanges();
            return RedirectToAction("ÜrünListesi");
        }

        public ActionResult UrunGetir(int id)
        {
            var value = db.TBL_URUNLER.Find(id);

            List<SelectListItem> degerler = (from i in db.TBL_KATEGORİLER.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.kategoriad,
                                                 Value = i.kategoriıd.ToString(),

                                             }).ToList();
            ViewBag.deger = degerler;

            return View("UrunGetir", value);
        }

        public ActionResult Guncelle(TBL_URUNLER p1)
        {
            var value = db.TBL_URUNLER.Find(p1.ürünıd);
            value.ürünadı = p1.ürünadı;
            value.marka = p1.marka;
            value.stok = p1.stok;
            //value.ürünkategorisi = p1.ürünkategorisi;
            var kategori = db.TBL_KATEGORİLER.Where(m => m.kategoriıd == p1.TBL_KATEGORİLER.kategoriıd).FirstOrDefault();
            value.ürünkategorisi = kategori.kategoriıd;
            value.fiyat = p1.fiyat;
            db.SaveChanges();
            return RedirectToAction("ÜrünListesi");
        }

    }
}

MvcStok/Views/Urunler/UrunGetir.cshtml
@model MvcStok.Models.Entity.TBL_URUNLER
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Ürün Güncelleme Sayfası</h2>

<br />

@using (Html.BeginForm("Guncelle", "Urunler", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(m => m.ürünıd, "ÜRÜN ID")
    @Html.TextBoxFor(m => m.ürünıd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.ürünadı, "ÜRÜN AD")
    @Html.TextBoxFor(m => m.ürünadı, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.marka, "MARKA")
    @Html.TextBoxFor(m => m.marka, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.ürünkategorisi, "KATEGORİ")
    @*@Html.TextBoxFor(m => m.ürünkategorisi, new { @class = "form-control" })*@

    @Html.DropDownListFor(m => m.TBL_KATEGORİLER.kategoriıd, (List<SelectListItem>)ViewBag.deger, new { @class = "form-control" })

    <br />
    @Html.LabelFor(m => m.fiyat, "FİYAT")
    @Html.TextBoxFor(m => m.fiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.stok, "STOK")
    @Html.TextBoxFor(m => m.stok, new { @class = "form-control" })
    <br />


</div>
    <div><button class="btn btn-warning">ÜRÜN GÜNCELLE</button></div>
}

MvcStok/Views/Urunler/YeniÜrün.cshtml
@model MvcStok.Models.Entity.TBL_URUNLER
@{
    ViewBag.Title = "YeniÜrün";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h3>Yeni Ürün Ekleme Sayfası</h3>
<br /><br />
<form class="form-group" method="post">
    <div>
        <label>ÜRÜN AD</label>
        <input type="text" class="form-control" name="ürünadı" required="" maxlength="30" />
        <br /><br />
        <label>MARKA</label>
        <input type="text" class="form-control" name="marka" placeholder="Buraya markayı yazınız." required="" />
        <br /><br />

        <label>KATEGORİ SEÇİNİZ</label>
        @*viewbagden taşımış olduğum değerleri getir.*@
        @Html.DropDownListFor(m=>m.TBL_KATEGORİLER.kategoriıd,(List<SelectListItem>)ViewBag.deger, new { @class="form-control"})
        <br /><br />

        <label>FİYAT</label>
        <input type="text" class="form-control" name="fiyat" />
        <br /><br />
        <label>STOK ADET</label>
        <input type="text" class="form-control" name="stok" />
        <br /><br />
        <button class="btn btn-info">ÜRÜN EKLE</button>
    </div>




</form>

MvcStok/Views/Urunler/ÜrünListesi.cshtml
@using MvcStok.Models.Entity
@model List<TBL_URUNLER>

@{
    ViewBag.Title = "ÜrünListesi";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<br />
@*@using (Html.BeginForm("ÜrünListesi", "Urunler", FormMethod.Get))
    {
        <p>
           <b> Aranacak Kelime:</b> @Html.TextBox("a")
            <input type="submit" value="Ara" class="btn btn-info"/>
        </p>


    }
    <br />*@
<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>
            <th>ÜRÜN ID</th>
            <th>ÜRÜN ADI</th>
            <th>ÜRÜN MARKASI</th>
            <th>ÜRÜN KATEGORİSİ</th>
            <th>ÜRÜN FİYATI</th>
            <th>ÜRÜN STOK ADETİ</th>
            <th>SİL</th>
            <th>GÜNCELLE</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ürünıd</td>
                <td>@item.ürünadı</td>
                <td>@item.marka</td>
                <td>@item.TBL_KATEGORİLER.kategoriad</td>
                <td>@item.fiyat</td>
                <td>@item.stok</td>
                <td><a href="/Urunler/Sil/@item.ürünıd" class="btn btn-danger">SİL</a></td>
                <td><a href="/Urunler/UrunGetir/@item.ürünıd" class="btn btn-success">GÜNCELLE</a></td>

            </tr>
        }

    </tbody>

</table>
<a href="/Urunler/YeniÜrün/" class="btn btn-info">YENİ ÜRÜN EKLE</a>

<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>


<link href="~/Content/DataTables/css/dataTables.jqueryui.min.css" rel="stylesheet" />





<script>
    $('#tbl1').DataTable();
</script>